**Q1**:  What are the similarities and differences between pandas and numpy? Include some type of example with code.

**Answer**: Both are used for handling and manipulating data and they provide data structures to work with multi-dimensional arrays. However, NumPy works with n-dimensional arrays while Pandas works with series and dataframes. Also, Pandas dataframes can contain elements of the same type (i.e. different columns can be different types) while NumPy ndarrays require all elements to be of the same type. NumPy can be used for mathematical operations and computing while Pandas can be used for data manipulation, data cleaning, data exploration, and data analysis. 

In [40]:
import numpy as np
import pandas as pd

# sample data
people = {
    "Name": ["Will", "Jess", "Nick", "Schmidt"],
    "Age": [33, 30, 34, 32]
}

# pandas dataframe can hold multiple data types
pd.DataFrame(people)

Name  Age
0     Will   33
1     Jess   30
2     Nick   34
3  Schmidt   32

In [41]:
# numpy array can only hold one type
np.array(people['Age'])

array([33, 30, 34, 32])

**Q2**: What is the ndarray in numPy?

**Answer**: It is a data storage object similar to a list but which can only store elements of the same type. 

**Q3**: Create a 1D array of numbers from 0 to 9 

Desired Output: 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
array1 = np.array(range(10))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Q4**: Extract all odd numbers from array1 

array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
odd = array1[array1 %2 != 0]
odd

array([1, 3, 5, 7, 9])

**Q5**: Get the common items between a and b  

Input:

    a = np.array([1,2,3,2,3,4,3,4,5,6])
    b = np.array([7,2,10,2,7,4,9,4,9,8])

Desired Output:

    array([2, 4])

In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

**Q6**: From array a remove all items present in array b 

Input:

    a = np.array([1,2,3,4,5])
    b = np.array([5,6,7,8,9])

Desired Output:

    array([1,2,3,4])

In [45]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

**Q7** Find out if iris has any missing values. 

Input:

    url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
    iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [46]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

iris[np.isnan(iris) == True]    # outputs empty array - no missing values

array([], dtype=float64)